"""
Diagnostic Layer Domain Models.
Strictly schema-validated LLM outputs for classification and ambiguity handling.
"""
from typing import List
from pydantic import BaseModel, Field
from src.core.types import FailureClass

class DiagnosticOutput(BaseModel):
    """
    Structured diagnosis generated by the LLM (or programmatic classifier).
    This strictly decouples LLM generation from execution logic (Constraint B5).
    """
    failure_class: FailureClass = Field(
        description="The resolved canonical failure class"
    )
    confidence: float = Field(
        ge=0.0, le=1.0, 
        description="Confidence score of the classification"
    )
    evidence: List[str] = Field(
        description="List of reasons or evidence justifying the classification"
    )
